name: 'action-org-repo-list'
description: 'Make organization repo list README'
author: 'Caijinglong'
inputs:
  github-token:
    required: true
    description: 'Github token'
  org:
    required: true
    description: 'Github organization, e.g. "fluttercandies"'
  exclude-repo-names:
    required: false
    description: 'Exclude glob pattern for repositories, e.g. ".github,docs", default: ".github"'
  contains-archived:
    required: false
    description: 'Contains archived repositories. default: false'
  wrap-with-details:
    required: true
    description: 'Wrap with details tag. default: true'

runs:
  using: 'node16'
  main: 'dist/index.js'
