name: Generate organization profile README.md

on:
  push:
    branches:
      - master
      - main
  schedule:
    # Run at every hour
    - cron: '0 * * * *'
  workflow_dispatch:

env:
#   ORG: fluttercandies
  ORG: flutter-fix-something

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: caijinglong/action-org-repo-list@main
        id: org_repo_list
        with:
          github-token: ${{ secrets.PERSON_TOKEN }}
          org: ${{ env.ORG }}
          exclude-repo-names: '.github,.github-workflow'
      - name: Generate README.md
        env:
          GH_TOKEN: ${{ secrets.PERSON_TOKEN }}
        run: |
          export TARGET_FILE=/tmp/.github/profile/README.md
          gh repo clone ${{ env.ORG }}/.github /tmp/.github
          cd /tmp/.github
          if [ -f "$TARGET_FILE" ]; then
            rm $TARGET_FILE
          fi
          touch $TARGET_FILE
          echo "## Welcome to the Flutter Candies organization\n" >> $TARGET_FILE
          echo "Custom Flutter Candies (packages) for you to build your Flutter app easily. Enjoy it!\n" >> $TARGET_FILE
          echo "## Organization Repositories\n" >> $TARGET_FILE
          echo "${{ steps.org_repo_list.outputs.table }}" >> $TARGET_FILE
          echo "\n" >> $TARGET_FILE
          git add .
          git commit -m "Update profile/README.md from CI"
          git push